const countriesAndCapitals = [
  { country: "Afghanistan", capital: "Kabul", continent: "Asia", code: "AF" },
  { country: "Albania", capital: "Tirana", continent: "Europe", code: "AL" },
  { country: "Algeria", capital: "Algiers", continent: "Africa", code: "DZ" },
  { country: "Andorra", capital: "Andorra la Vella", continent: "Europe", code: "AD" },
  { country: "Angola", capital: "Luanda", continent: "Africa", code: "AO" },
  { country: "Antigua and Barbuda", capital: "Saint John's", continent: "North America", code: "AG" },
  { country: "Argentina", capital: "Buenos Aires", continent: "South America", code: "AR" },
  { country: "Armenia", capital: "Yerevan", continent: "Asia", code: "AM" },
  { country: "Australia", capital: "Canberra", continent: "Australia", code: "AU" },
  { country: "Austria", capital: "Vienna", continent: "Europe", code: "AT" },
  { country: "Azerbaijan", capital: "Baku", continent: "Asia", code: "AZ" },
  { country: "Bahamas", capital: "Nassau", continent: "North America", code: "BS" },
  { country: "Bahrain", capital: "Manama", continent: "Asia", code: "BH" },
  { country: "Bangladesh", capital: "Dhaka", continent: "Asia", code: "BD" },
  { country: "Barbados", capital: "Bridgetown", continent: "North America", code: "BB" },
  { country: "Belarus", capital: "Minsk", continent: "Europe", code: "BY" },
  { country: "Belgium", capital: "Brussels", continent: "Europe", code: "BE" },
  { country: "Belize", capital: "Belmopan", continent: "North America", code: "BZ" },
  { country: "Benin", capital: "Porto-Novo", continent: "Africa", code: "BJ" },
  { country: "Bhutan", capital: "Thimphu", continent: "Asia", code: "BT" },
  { country: "Bolivia", capital: "Sucre", continent: "South America", code: "BO" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", continent: "Europe", code: "BA" },
  { country: "Botswana", capital: "Gaborone", continent: "Africa", code: "BW" },
  { country: "Brazil", capital: "Brasilia", continent: "South America", code: "BR" },
  { country: "Brunei", capital: "Bandar Seri Begawan", continent: "Asia", code: "BN" },
  { country: "Bulgaria", capital: "Sofia", continent: "Europe", code: "BG" },
  { country: "Burkina Faso", capital: "Ouagadougou", continent: "Africa", code: "BF" },
  { country: "Burundi", capital: "Gitega", continent: "Africa", code: "BI" },
  { country: "Cape Verde", capital: "Praia", continent: "Africa", code: "CV" },
  { country: "Cambodia", capital: "Phnom Penh", continent: "Asia", code: "KH" },
  { country: "Cameroon", capital: "Yaoundé", continent: "Africa", code: "CM" },
  { country: "Canada", capital: "Ottawa", continent: "North America", code: "CA" },
  { country: "Central African Republic", capital: "Bangui", continent: "Africa", code: "CF" },
  { country: "Chad", capital: "N'Djamena", continent: "Africa", code: "TD" },
  { country: "Chile", capital: "Santiago", continent: "South America", code: "CL" },
  { country: "China", capital: "Beijing", continent: "Asia", code: "CN" },
  { country: "Colombia", capital: "Bogotá", continent: "South America", code: "CO" },
  { country: "Comoros", capital: "Moroni", continent: "Africa", code: "KM" },
  { country: "Democratic Republic of the Congo", capital: "Kinshasa", continent: "Africa", code: "CD" },
  { country: "Republic of Congo", capital: "Brazzaville", continent: "Africa", code: "CG" },
  { country: "Costa Rica", capital: "San José", continent: "North America", code: "CR" },
  { country: "Croatia", capital: "Zagreb", continent: "Europe", code: "HR" },
  { country: "Cuba", capital: "Havana", continent: "North America", code: "CU" },
  { country: "Cyprus", capital: "Nicosia", continent: "Asia", code: "CY" },
  { country: "Czech Republic", capital: "Prague", continent: "Europe", code: "CZ" },
  { country: "Denmark", capital: "Copenhagen", continent: "Europe", code: "DK" },
  { country: "Djibouti", capital: "Djibouti", continent: "Africa", code: "DJ" },
  { country: "Dominica", capital: "Roseau", continent: "North America", code: "DM" },
  { country: "Dominican Republic", capital: "Santo Domingo", continent: "North America", code: "DO" },
  { country: "East Timor", capital: "Dili", continent: "Asia", code: "TL" },
  { country: "Ecuador", capital: "Quito", continent: "South America", code: "EC" },
  { country: "Egypt", capital: "Cairo", continent: "Africa", code: "EG" },
  { country: "El Salvador", capital: "San Salvador", continent: "North America", code: "SV" },
  { country: "Equatorial Guinea", capital: "Malabo", continent: "Africa", code: "GQ" },
  { country: "Eritrea", capital: "Asmara", continent: "Africa", code: "ER" },
  { country: "Estonia", capital: "Tallinn", continent: "Europe", code: "EE" },
  { country: "Eswatini", capital: "Mbabane", continent: "Africa", code: "SZ" },
  { country: "Ethiopia", capital: "Addis Ababa", continent: "Africa", code: "ET" },
  { country: "Fiji", capital: "Suva", continent: "Australia", code: "FJ" },
  { country: "Finland", capital: "Helsinki", continent: "Europe", code: "FI" },
  { country: "France", capital: "Paris", continent: "Europe", code: "FR" },
  { country: "Gabon", capital: "Libreville", continent: "Africa", code: "GA" },
  { country: "Gambia", capital: "Banjul", continent: "Africa", code: "GM" },
  { country: "Georgia", capital: "Tbilisi", continent: "Asia", code: "GE" },
  { country: "Germany", capital: "Berlin", continent: "Europe", code: "DE" },
  { country: "Ghana", capital: "Accra", continent: "Africa", code: "GH" },
  { country: "Greece", capital: "Athens", continent: "Europe", code: "GR" },
  { country: "Grenada", capital: "St. George's", continent: "North America", code: "GD" },
  { country: "Guatemala", capital: "Guatemala City", continent: "North America", code: "GT" },
  { country: "Guinea", capital: "Conakry", continent: "Africa", code: "GN" },
  { country: "Guinea-Bissau", capital: "Bissau", continent: "Africa", code: "GW" },
  { country: "Guyana", capital: "Georgetown", continent: "South America", code: "GY" },
  { country: "Haiti", capital: "Port-au-Prince", continent: "North America", code: "HT" },
  { country: "Honduras", capital: "Tegucigalpa", continent: "North America", code: "HN" },
  { country: "Hungary", capital: "Budapest", continent: "Europe", code: "HU" },
  { country: "Iceland", capital: "Reykjavik", continent: "Europe", code: "IS" },
  { country: "India", capital: "New Delhi", continent: "Asia", code: "IN" },
  { country: "Indonesia", capital: "Jakarta", continent: "Asia", code: "ID" },
  { country: "Iran", capital: "Tehran", continent: "Asia", code: "IR" },
  { country: "Iraq", capital: "Baghdad", continent: "Asia", code: "IQ" },
  { country: "Ireland", capital: "Dublin", continent: "Europe", code: "IE" },
  { country: "Israel", capital: "Jerusalem", continent: "Asia", code: "IL" },
  { country: "Italy", capital: "Rome", continent: "Europe", code: "IT" },
  { country: "Ivory Coast", capital: "Yamoussoukro", continent: "Africa", code: "CI" },
  { country: "Jamaica", capital: "Kingston", continent: "North America", code: "JM" },
  { country: "Japan", capital: "Tokyo", continent: "Asia", code: "JP" },
  { country: "Jordan", capital: "Amman", continent: "Asia", code: "JO" },
  { country: "Kosovo", capital: "Pristina", continent: "Europe", code: "XK" },
  { country: "Kazakhstan", capital: "Nur-Sultan", continent: "Asia", code: "KZ" },
  { country: "Kenya", capital: "Nairobi", continent: "Africa", code: "KE" },
  { country: "Kiribati", capital: "South Tarawa", continent: "Australia", code: "KI" },
  { country: "Kuwait", capital: "Kuwait City", continent: "Asia", code: "KW" },
  { country: "Kyrgyzstan", capital: "Bishkek", continent: "Asia", code: "KG" },
  { country: "Lao PDR", capital: "Vientiane", continent: "Asia", code: "LA" },
  { country: "Latvia", capital: "Riga", continent: "Europe", code: "LV" },
  { country: "Lebanon", capital: "Beirut", continent: "Asia", code: "LB" },
  { country: "Lesotho", capital: "Maseru", continent: "Africa", code: "LS" },
  { country: "Liberia", capital: "Monrovia", continent: "Africa", code: "LR" },
  { country: "Libya", capital: "Tripoli", continent: "Africa", code: "LY" },
  { country: "Liechtenstein", capital: "Vaduz", continent: "Europe", code: "LI" },
  { country: "Lithuania", capital: "Vilnius", continent: "Europe", code: "LT" },
  { country: "Luxembourg", capital: "Luxembourg", continent: "Europe", code: "LU" },
  { country: "Madagascar", capital: "Antananarivo", continent: "Africa", code: "MG" },
  { country: "Malawi", capital: "Lilongwe", continent: "Africa", code: "MW" },
  { country: "Malaysia", capital: "Kuala Lumpur", continent: "Asia", code: "MY" },
  { country: "Maldives", capital: "Malé", continent: "Asia", code: "MV" },
  { country: "Mali", capital: "Bamako", continent: "Africa", code: "ML" },
  { country: "Malta", capital: "Valletta", continent: "Europe", code: "MT" },
  { country: "Marshall Islands", capital: "Majuro", continent: "Australia", code: "MH" },
  { country: "Mauritania", capital: "Nouakchott", continent: "Africa", code: "MR" },
  { country: "Mauritius", capital: "Port Louis", continent: "Africa", code: "MU" },
  { country: "Mexico", capital: "Mexico City", continent: "North America", code: "MX" },
  { country: "Micronesia", capital: "Palikir", continent: "Australia", code: "FM" },
  { country: "Moldova", capital: "Chișinău", continent: "Europe", code: "MD" },
  { country: "Monaco", capital: "Monaco", continent: "Europe", code: "MC" },
  { country: "Mongolia", capital: "Ulaanbaatar", continent: "Asia", code: "MN" },
  { country: "Montenegro", capital: "Podgorica", continent: "Europe", code: "ME" },
  { country: "Morocco", capital: "Rabat", continent: "Africa", code: "MA" },
  { country: "Mozambique", capital: "Maputo", continent: "Africa", code: "MZ" },
  { country: "Myanmar", capital: "Naypyidaw", continent: "Asia", code: "MM" },
  { country: "Namibia", capital: "Windhoek", continent: "Africa", code: "NA" },
  { country: "Nauru", capital: "Yaren", continent: "Australia", code: "NR" },
  { country: "Nepal", capital: "Kathmandu", continent: "Asia", code: "NP" },
  { country: "Netherlands", capital: "Amsterdam", continent: "Europe", code: "NL" },
  { country: "New Zealand", capital: "Wellington", continent: "Australia", code: "NZ" },
  { country: "Nicaragua", capital: "Managua", continent: "North America", code: "NI" },
  { country: "Niger", capital: "Niamey", continent: "Africa", code: "NE" },
  { country: "Nigeria", capital: "Abuja", continent: "Africa", code: "NG" },
  { country: "Macedonia", capital: "Skopje", continent: "Europe", code: "MK" },
  { country: "Norway", capital: "Oslo", continent: "Europe", code: "NO" },
  { country: "Oman", capital: "Muscat", continent: "Asia", code: "OM" },
  { country: "Pakistan", capital: "Islamabad", continent: "Asia", code: "PK" },
  { country: "Palau", capital: "Ngerulmud", continent: "Australia", code: "PW" },
  { country: "Panama", capital: "Panama City", continent: "North America", code: "PA" },
  { country: "Papua New Guinea", capital: "Port Moresby", continent: "Australia", code: "PG" },
  { country: "Paraguay", capital: "Asunción", continent: "South America", code: "PY" },
  { country: "Peru", capital: "Lima", continent: "South America", code: "PE" },
  { country: "Philippines", capital: "Manila", continent: "Asia", code: "PH" },
  { country: "Poland", capital: "Warsaw", continent: "Europe", code: "PL" },
  { country: "Portugal", capital: "Lisbon", continent: "Europe", code: "PT" },
  { country: "Qatar", capital: "Doha", continent: "Asia", code: "QA" },
  { country: "Romania", capital: "Bucharest", continent: "Europe", code: "RO" },
  { country: "Russia", capital: "Moscow", continent: "Europe", code: "RU" },
  { country: "Rwanda", capital: "Kigali", continent: "Africa", code: "RW" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", continent: "North America", code: "KN" },
  { country: "Saint Lucia", capital: "Castries", continent: "North America", code: "LC" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", continent: "North America", code: "VC" },
  { country: "Samoa", capital: "Apia", continent: "Australia", code: "WS" },
  { country: "San Marino", capital: "San Marino", continent: "Europe", code: "SM" },
  { country: "Sao Tome and Principe", capital: "São Tomé", continent: "Africa", code: "ST" },
  { country: "Saudi Arabia", capital: "Riyadh", continent: "Asia", code: "SA" },
  { country: "Senegal", capital: "Dakar", continent: "Africa", code: "SN" },
  { country: "Serbia", capital: "Belgrade", continent: "Europe", code: "RS" },
  { country: "Seychelles", capital: "Victoria", continent: "Africa", code: "SC" },
  { country: "Sierra Leone", capital: "Freetown", continent: "Africa", code: "SL" },
  { country: "Singapore", capital: "Singapore", continent: "Asia", code: "SG" },
  { country: "Slovakia", capital: "Bratislava", continent: "Europe", code: "SK" },
  { country: "Slovenia", capital: "Ljubljana", continent: "Europe", code: "SI" },
  { country: "Solomon Islands", capital: "Honiara", continent: "Australia", code: "SB" },
  { country: "Somalia", capital: "Mogadishu", continent: "Africa", code: "SO" },
  { country: "South Africa", capital: "Pretoria", continent: "Africa", code: "ZA" },
  { country: "South Korea", capital: "Seoul", continent: "Asia", code: "KR" },
  { country: "South Sudan", capital: "Juba", continent: "Africa", code: "SS" },
  { country: "Spain", capital: "Madrid", continent: "Europe", code: "ES" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: "Asia", code: "LK" },
  { country: "Sudan", capital: "Khartoum", continent: "Africa", code: "SD" },
  { country: "Suriname", capital: "Paramaribo", continent: "South America", code: "SR" },
  { country: "Sweden", capital: "Stockholm", continent: "Europe", code: "SE" },
  { country: "Switzerland", capital: "Bern", continent: "Europe", code: "CH" },
  { country: "Syria", capital: "Damascus", continent: "Asia", code: "SY" },
  { country: "Taiwan", capital: "Taipei", continent: "Asia", code: "TW" },
  { country: "Tajikistan", capital: "Dushanbe", continent: "Asia", code: "TJ" },
  { country: "Tanzania", capital: "Dodoma", continent: "Africa", code: "TZ" },
  { country: "Thailand", capital: "Bangkok", continent: "Asia", code: "TH" },
  { country: "Togo", capital: "Lomé", continent: "Africa", code: "TG" },
  { country: "Tonga", capital: "Nukuʻalofa", continent: "Australia", code: "TO" },
  { country: "Trinidad and Tobago", capital: "Port of Spain", continent: "North America", code: "TT" },
  { country: "Tunisia", capital: "Tunis", continent: "Africa", code: "TN" },
  { country: "Turkey", capital: "Ankara", continent: "Asia", code: "TR" },
  { country: "Turkmenistan", capital: "Ashgabat", continent: "Asia", code: "TM" },
  { country: "Tuvalu", capital: "Funafuti", continent: "Australia", code: "TV" },
  { country: "Uganda", capital: "Kampala", continent: "Africa", code: "UG" },
  { country: "Ukraine", capital: "Kyiv", continent: "Europe", code: "UA" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", continent: "Asia", code: "AE" },
  { country: "United Kingdom", capital: "London", continent: "Europe", code: "GB" },
  { country: "United States", capital: "Washington, D.C.", continent: "North America", code: "US" },
  { country: "Uruguay", capital: "Montevideo", continent: "South America", code: "UY" },
  { country: "Uzbekistan", capital: "Tashkent", continent: "Asia", code: "UZ" },
  { country: "Vanuatu", capital: "Port Vila", continent: "Australia", code: "VU" },
  { country: "Vatican City", capital: "Vatican City", continent: "Europe", code: "VA" },
  { country: "Venezuela", capital: "Caracas", continent: "South America", code: "VE" },
  { country: "Vietnam", capital: "Hanoi", continent: "Asia", code: "VN" },
  { country: "Yemen", capital: "Sana'a", continent: "Asia", code: "YE" },
  { country: "Zambia", capital: "Lusaka", continent: "Africa", code: "ZM" },
  { country: "Zimbabwe", capital: "Harare", continent: "Africa", code: "ZW" }
];
